require("./dashboard")
// require("./penerima")
require("./master-pemohon")
require("./register-proposal")
require("./register-survey")
require("./register-surveyor")
require("./proposal")
require("./analisa-proposal")
